#!/bin/sh
set -e

# Bootstrap secrets, generate vox config, start omegon daemon.
#
# Required:
#   ANTHROPIC_API_KEY (or OPENAI_API_KEY, or mounted auth.json)
#   VOX_DISCORD_BOT_TOKEN
#
# Optional config overrides:
#   VOX_DISCORD_OPERATORS=id1,id2       → operators = ["id1", "id2"]
#   VOX_DISCORD_OPERATOR_ROLES=r1,r2    → operator_roles = ["r1", "r2"]
#   VOX_DISCORD_ALLOWED_USERS=id1,id2   → allowed_users = ["id1", "id2"]
#   VOX_DISCORD_GUILD_ID=123456789      → guild_id = "123456789"
#   VOX_DISCORD_REQUIRE_MENTION=false   → require_mention = false
#
# Vault-backed secrets (requires VAULT_ADDR + VAULT_TOKEN):
#   VOX_DISCORD_BOT_TOKEN_VAULT=secret/data/vox/discord#bot_token
#   ANTHROPIC_API_KEY_VAULT=secret/data/omegon/api#anthropic

OMEGON_HOME="${OMEGON_HOME:-/data/omegon}"
OMEGON_CONFIG="${OMEGON_CONFIG:-/config/omegon}"
SECRETS_JSON="${OMEGON_HOME}/secrets.json"
VOX_TOML="/root/.config/vox/vox.toml"

mkdir -p "${OMEGON_HOME}" "/root/.config/vox"

# ── Vox config generation ─────────────────────────────────────────────

csv_to_toml_array() {
    local csv="$1"
    if [ -z "$csv" ]; then echo "[]"; return; fi
    printf '['
    first=true
    IFS=','
    for item in $csv; do
        item="$(echo "$item" | xargs)"
        if [ -n "$item" ]; then
            if [ "$first" = true ]; then first=false; else printf ', '; fi
            printf '"%s"' "$item"
        fi
    done
    unset IFS
    printf ']'
}

generate_discord_config() {
    local has_env=false
    for var in VOX_DISCORD_BOT_TOKEN VOX_DISCORD_OPERATORS VOX_DISCORD_OPERATOR_ROLES \
               VOX_DISCORD_GUILD_ID VOX_DISCORD_REQUIRE_MENTION VOX_DISCORD_ALLOWED_USERS; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_env=true; break
        fi
    done

    if [ "$has_env" = false ]; then return 1; fi

    local require_mention="${VOX_DISCORD_REQUIRE_MENTION:-true}"
    local guild_id="${VOX_DISCORD_GUILD_ID:-}"
    local operators="$(csv_to_toml_array "${VOX_DISCORD_OPERATORS:-}")"
    local operator_roles="$(csv_to_toml_array "${VOX_DISCORD_OPERATOR_ROLES:-}")"
    local allowed_users="$(csv_to_toml_array "${VOX_DISCORD_ALLOWED_USERS:-}")"

    echo "Generating vox.toml from environment..."
    cat > "${VOX_TOML}" <<EOF
# Generated by entrypoint.sh
[discord]
require_mention = ${require_mention}
operators = ${operators}
operator_roles = ${operator_roles}
allowed_users = ${allowed_users}
EOF

    if [ -n "$guild_id" ]; then
        echo "guild_id = \"${guild_id}\"" >> "${VOX_TOML}"
    fi

    echo "  discord: operators=${operators} operator_roles=${operator_roles}"
    return 0
}

if ! generate_discord_config; then
    echo "Using baked-in vox.toml"
fi

# ── Secrets bootstrap ─────────────────────────────────────────────────
echo "{}" > "${SECRETS_JSON}"
chmod 600 "${SECRETS_JSON}"

write_recipe() {
    local name="$1" recipe="$2"
    local current
    current="$(cat "${SECRETS_JSON}")"
    if [ "$current" = "{}" ]; then
        echo "{\"${name}\": \"${recipe}\"}" > "${SECRETS_JSON}"
    else
        sed -i 's|}$|,"'"${name}"'": "'"${recipe}"'"}|' "${SECRETS_JSON}"
    fi
}

add_recipe() {
    local name="$1"
    local vault_var="${name}_VAULT"
    local vault_path
    vault_path="$(printenv "$vault_var" 2>/dev/null || true)"
    if [ -n "$vault_path" ]; then
        write_recipe "$name" "vault:${vault_path}"
        echo "  ${name} -> vault:${vault_path}"
        return
    fi
    local val
    val="$(printenv "$name" 2>/dev/null || true)"
    if [ -n "$val" ]; then
        write_recipe "$name" "env:${name}"
        echo "  ${name} -> env:${name}"
    fi
}

echo "Configuring secrets..."
add_recipe "ANTHROPIC_API_KEY"
add_recipe "OPENAI_API_KEY"
add_recipe "VOX_DISCORD_BOT_TOKEN"
chmod 600 "${SECRETS_JSON}"

# ── Auth validation ───────────────────────────────────────────────────
HAS_CREDENTIALS=false

for var in ANTHROPIC_API_KEY OPENAI_API_KEY OPENROUTER_API_KEY \
           ANTHROPIC_API_KEY_VAULT OPENAI_API_KEY_VAULT OPENROUTER_API_KEY_VAULT; do
    if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
        HAS_CREDENTIALS=true; break
    fi
done

AUTH_JSON="${OMEGON_CONFIG}/auth.json"
if [ -f "$AUTH_JSON" ]; then
    HAS_CREDENTIALS=true
    echo "  auth.json mounted at ${AUTH_JSON}"
    mkdir -p "${HOME}/.config/omegon"
    ln -sf "${AUTH_JSON}" "${HOME}/.config/omegon/auth.json"
fi

if [ "$HAS_CREDENTIALS" = false ] && grep -q '"vault:' "${SECRETS_JSON}" 2>/dev/null; then
    HAS_CREDENTIALS=true
    echo "  vault-backed credentials configured"
fi

if [ "$HAS_CREDENTIALS" = false ]; then
    echo "ERROR: No LLM credentials found."
    echo "  Provide one of:"
    echo "    -e ANTHROPIC_API_KEY=sk-..."
    echo "    -e ANTHROPIC_API_KEY_VAULT=secret/data/omegon/api#anthropic"
    echo "    -v ~/.config/omegon:/config/omegon:ro  (for OAuth tokens)"
    exit 1
fi

if [ -z "$(printenv VOX_DISCORD_BOT_TOKEN 2>/dev/null || true)" ] \
   && [ -z "$(printenv VOX_DISCORD_BOT_TOKEN_VAULT 2>/dev/null || true)" ]; then
    echo "WARNING: VOX_DISCORD_BOT_TOKEN not set — bot will not connect"
fi

# ── Start ──────────────────────────────────────────────────────────────
echo "Starting omegon daemon..."
exec omegon serve --control-port 7842 "$@"
