#!/bin/sh
set -e

# Bootstrap secrets, generate vox config from env, start omegon serve.
#
# ── LLM Auth ──────────────────────────────────────────────────────────
#   1. API key via env var (ANTHROPIC_API_KEY, OPENAI_API_KEY, etc.)
#   2. OAuth via mounted auth.json (~/.config/omegon/auth.json)
#      Mount: -v ~/.config/omegon:/config/omegon:ro
#
# ── Secrets ───────────────────────────────────────────────────────────
# Each secret supports three resolution modes (checked in this order):
#
#   1. Vault:  FOO_VAULT=secret/data/path#key  → vault: recipe
#              Requires VAULT_ADDR + (VAULT_TOKEN or k8s auth)
#   2. Env:    FOO=raw-value                   → env: recipe
#   3. Absent: secret not configured, connector degrades gracefully
#
# Examples:
#   -e VOX_DISCORD_BOT_TOKEN_VAULT=secret/data/vox/discord#bot_token
#   -e VOX_DISCORD_BOT_TOKEN=xoxb-...
#   -e ANTHROPIC_API_KEY_VAULT=secret/data/omegon/api#anthropic
#   -e VAULT_ADDR=https://vault.example.com
#   -e VAULT_TOKEN=hvs.xxx
#
# ── Connector Config ──────────────────────────────────────────────────
# Env vars override baked-in vox.toml (non-sensitive, no Vault needed):
#   VOX_DISCORD_OPERATORS=id1,id2       → operators = ["id1", "id2"]
#   VOX_DISCORD_OPERATOR_ROLES=r1,r2    → operator_roles = ["r1", "r2"]
#   VOX_DISCORD_ALLOWED_USERS=id1,id2   → allowed_users = ["id1", "id2"]
#   VOX_DISCORD_GUILD_ID=123            → guild_id = "123"
#   VOX_DISCORD_REQUIRE_MENTION=false   → require_mention = false
#
#   VOX_SLACK_OPERATORS=id1,id2         → operators = ["id1", "id2"]
#   VOX_SLACK_OPERATOR_GROUPS=g1,g2     → operator_groups = ["g1", "g2"]
#   VOX_SLACK_ALLOWED_USERS=id1,id2     → allowed_users = ["id1", "id2"]
#   VOX_SLACK_WORKSPACE=name            → workspace = "name"

OMEGON_HOME="${OMEGON_HOME:-/data/omegon}"
OMEGON_CONFIG="${OMEGON_CONFIG:-/config/omegon}"
SECRETS_JSON="${OMEGON_HOME}/secrets.json"
VOX_TOML="/root/.config/vox/vox.toml"

mkdir -p "${OMEGON_HOME}" "/root/.config/vox"

# ── Vox config generation ─────────────────────────────────────────────
# If any VOX_DISCORD_* or VOX_SLACK_* env vars are set, generate vox.toml
# from env. Otherwise, use the baked-in config.

# Helper: convert comma-separated string to TOML array
csv_to_toml_array() {
    local csv="$1"
    if [ -z "$csv" ]; then
        echo "[]"
        return
    fi
    printf '['
    first=true
    IFS=','
    for item in $csv; do
        item="$(echo "$item" | xargs)"  # trim whitespace
        if [ -n "$item" ]; then
            if [ "$first" = true ]; then first=false; else printf ', '; fi
            printf '"%s"' "$item"
        fi
    done
    unset IFS
    printf ']'
}

generate_vox_config() {
    local has_discord=false
    local has_slack=false

    # Check if any connector env vars are set
    for var in VOX_DISCORD_BOT_TOKEN VOX_DISCORD_OPERATORS VOX_DISCORD_OPERATOR_ROLES \
               VOX_DISCORD_GUILD_ID VOX_DISCORD_REQUIRE_MENTION VOX_DISCORD_ALLOWED_USERS; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_discord=true
            break
        fi
    done
    for var in VOX_SLACK_BOT_TOKEN VOX_SLACK_OPERATORS VOX_SLACK_OPERATOR_GROUPS \
               VOX_SLACK_WORKSPACE VOX_SLACK_ALLOWED_USERS; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_slack=true
            break
        fi
    done

    if [ "$has_discord" = false ] && [ "$has_slack" = false ]; then
        return 1  # no env vars set, use baked-in config
    fi

    echo "Generating vox.toml from environment..."
    cat > "${VOX_TOML}" <<VOXEOF
# Generated by entrypoint.sh from environment variables
VOXEOF

    if [ "$has_discord" = true ]; then
        local require_mention="${VOX_DISCORD_REQUIRE_MENTION:-true}"
        local guild_id="${VOX_DISCORD_GUILD_ID:-}"
        local operators="$(csv_to_toml_array "${VOX_DISCORD_OPERATORS:-}")"
        local operator_roles="$(csv_to_toml_array "${VOX_DISCORD_OPERATOR_ROLES:-}")"
        local allowed_users="$(csv_to_toml_array "${VOX_DISCORD_ALLOWED_USERS:-}")"

        cat >> "${VOX_TOML}" <<VOXEOF

[discord]
require_mention = ${require_mention}
operators = ${operators}
operator_roles = ${operator_roles}
allowed_users = ${allowed_users}
VOXEOF

        if [ -n "$guild_id" ]; then
            echo "guild_id = \"${guild_id}\"" >> "${VOX_TOML}"
        fi

        echo "  discord: operators=${operators} operator_roles=${operator_roles}"
    fi

    if [ "$has_slack" = true ]; then
        local workspace="${VOX_SLACK_WORKSPACE:-default}"
        local require_mention="${VOX_SLACK_REQUIRE_MENTION:-true}"
        local operators="$(csv_to_toml_array "${VOX_SLACK_OPERATORS:-}")"
        local operator_groups="$(csv_to_toml_array "${VOX_SLACK_OPERATOR_GROUPS:-}")"
        local allowed_users="$(csv_to_toml_array "${VOX_SLACK_ALLOWED_USERS:-}")"

        cat >> "${VOX_TOML}" <<VOXEOF

[slack]
workspace = "${workspace}"
require_mention = ${require_mention}
operators = ${operators}
operator_groups = ${operator_groups}
allowed_users = ${allowed_users}
VOXEOF

        echo "  slack: operators=${operators} operator_groups=${operator_groups}"
    fi

    return 0
}

# Try env-based config first, fall back to baked-in
if ! generate_vox_config; then
    echo "Using baked-in vox.toml"
fi

# ── Secrets bootstrap ─────────────────────────────────────────────────
echo "{}" > "${SECRETS_JSON}"
chmod 600 "${SECRETS_JSON}"

# Write a recipe to secrets.json. Args: secret_name, recipe_string
write_recipe() {
    local name="$1"
    local recipe="$2"
    local current
    current="$(cat "${SECRETS_JSON}")"
    if [ "$current" = "{}" ]; then
        echo "{\"${name}\": \"${recipe}\"}" > "${SECRETS_JSON}"
    else
        # Use | as sed delimiter — vault paths contain /
        sed -i 's|}$|,"'"${name}"'": "'"${recipe}"'"}|' "${SECRETS_JSON}"
    fi
}

# Add a secret recipe. Resolution order:
#   1. FOO_VAULT=secret/data/path#key → vault: recipe
#   2. FOO=raw-value                  → env: recipe
#   3. (neither set)                  → skip
add_recipe() {
    local name="$1"
    local vault_var="${name}_VAULT"
    local vault_path
    vault_path="$(printenv "$vault_var" 2>/dev/null || true)"

    if [ -n "$vault_path" ]; then
        write_recipe "$name" "vault:${vault_path}"
        echo "  ${name} -> vault:${vault_path}"
        return
    fi

    local val
    val="$(printenv "$name" 2>/dev/null || true)"
    if [ -n "$val" ]; then
        write_recipe "$name" "env:${name}"
        echo "  ${name} -> env:${name}"
    fi
}

echo "Configuring secrets..."
add_recipe "ANTHROPIC_API_KEY"
add_recipe "OPENAI_API_KEY"
add_recipe "VOX_DISCORD_BOT_TOKEN"
add_recipe "VOX_SLACK_BOT_TOKEN"
add_recipe "VOX_SLACK_APP_TOKEN"
add_recipe "VOX_SIGNAL_PASSWORD"
add_recipe "VOX_EMAIL_PASSWORD"
add_recipe "VOX_MATRIX_PASSWORD"
add_recipe "VOX_LXMF_IDENTITY"
chmod 600 "${SECRETS_JSON}"

# ── Auth validation ───────────────────────────────────────────────────
AUTH_JSON="${OMEGON_CONFIG}/auth.json"
HAS_CREDENTIALS=false

# Check env vars (direct or vault-backed)
for var in ANTHROPIC_API_KEY OPENAI_API_KEY OPENROUTER_API_KEY \
           ANTHROPIC_API_KEY_VAULT OPENAI_API_KEY_VAULT OPENROUTER_API_KEY_VAULT; do
    if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
        HAS_CREDENTIALS=true
        break
    fi
done

# Check mounted auth.json (OAuth tokens)
AUTH_JSON="${OMEGON_CONFIG}/auth.json"
if [ -f "$AUTH_JSON" ]; then
    HAS_CREDENTIALS=true
    echo "  auth.json mounted at ${AUTH_JSON}"
    mkdir -p "${HOME}/.config/omegon"
    ln -sf "${AUTH_JSON}" "${HOME}/.config/omegon/auth.json"
fi

# Check if Vault is configured (secrets.json has vault: recipes)
if [ "$HAS_CREDENTIALS" = false ] && grep -q '"vault:' "${SECRETS_JSON}" 2>/dev/null; then
    HAS_CREDENTIALS=true
    echo "  vault-backed credentials configured"
fi

if [ "$HAS_CREDENTIALS" = false ]; then
    echo "ERROR: No LLM credentials found."
    echo "  Provide one of:"
    echo "    -e ANTHROPIC_API_KEY=sk-..."
    echo "    -e ANTHROPIC_API_KEY_VAULT=secret/data/omegon/api#anthropic"
    echo "    -v ~/.config/omegon:/config/omegon:ro  (for OAuth tokens)"
    exit 1
fi

if [ -z "$(printenv VOX_DISCORD_BOT_TOKEN 2>/dev/null || true)" ] \
   && [ -z "$(printenv VOX_DISCORD_BOT_TOKEN_VAULT 2>/dev/null || true)" ]; then
    echo "  note: VOX_DISCORD_BOT_TOKEN not set — Discord connector will be degraded"
fi

# ── Start ──────────────────────────────────────────────────────────────
echo "Starting omegon daemon..."
exec omegon serve --control-port 7842 "$@"
