#!/bin/sh
set -e

# Bootstrap secrets, generate vox proxy config, start omegon daemon.
#
# Required:
#   ANTHROPIC_API_KEY (or OPENAI_API_KEY, or mounted auth.json)
#   VOX_SLACK_USER_TOKEN  (xoxp-* User OAuth Token)
#
# Optional config overrides:
#   VOX_SLACK_WORKSPACE=my-workspace    → workspace = "my-workspace"
#   VOX_SLACK_POSTURE=participate       → posture = "participate" (enables sending)
#   VOX_SLACK_WATCH_CHANNELS=C01,C02   → watch_channels = ["C01", "C02"]
#   VOX_SLACK_PROXY_POLL_SECS=30       → proxy_poll_secs = 30
#
# Vault-backed secrets (requires VAULT_ADDR + VAULT_TOKEN):
#   VOX_SLACK_USER_TOKEN_VAULT=secret/data/vox/slack#user_token

OMEGON_HOME="${OMEGON_HOME:-/data/omegon}"
OMEGON_CONFIG="${OMEGON_CONFIG:-/config/omegon}"
SECRETS_JSON="${OMEGON_HOME}/secrets.json"
VOX_TOML="/root/.config/vox/vox.toml"

mkdir -p "${OMEGON_HOME}" "/root/.config/vox"

# ── Vox config generation ─────────────────────────────────────────────

csv_to_toml_array() {
    local csv="$1"
    if [ -z "$csv" ]; then echo "[]"; return; fi
    printf '['
    first=true
    IFS=','
    for item in $csv; do
        item="$(echo "$item" | xargs)"
        if [ -n "$item" ]; then
            if [ "$first" = true ]; then first=false; else printf ', '; fi
            printf '"%s"' "$item"
        fi
    done
    unset IFS
    printf ']'
}

generate_proxy_config() {
    local has_env=false
    for var in VOX_SLACK_USER_TOKEN VOX_SLACK_WORKSPACE VOX_SLACK_POSTURE \
               VOX_SLACK_WATCH_CHANNELS VOX_SLACK_PROXY_POLL_SECS; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_env=true; break
        fi
    done

    if [ "$has_env" = false ]; then return 1; fi

    local workspace="${VOX_SLACK_WORKSPACE:-default}"
    local posture="${VOX_SLACK_POSTURE:-observe}"
    local poll_secs="${VOX_SLACK_PROXY_POLL_SECS:-30}"
    local watch_channels="$(csv_to_toml_array "${VOX_SLACK_WATCH_CHANNELS:-}")"

    echo "Generating proxy vox.toml from environment..."
    cat > "${VOX_TOML}" <<EOF
# Generated by entrypoint.sh
[slack]
workspace = "${workspace}"
mode = "proxy"
posture = "${posture}"
watch_channels = ${watch_channels}
proxy_poll_secs = ${poll_secs}
EOF

    echo "  proxy: posture=${posture} watch_channels=${watch_channels}"
    return 0
}

if ! generate_proxy_config; then
    echo "Using baked-in vox.toml"
fi

# ── Secrets bootstrap ─────────────────────────────────────────────────
echo "{}" > "${SECRETS_JSON}"
chmod 600 "${SECRETS_JSON}"

write_recipe() {
    local name="$1" recipe="$2"
    local current
    current="$(cat "${SECRETS_JSON}")"
    if [ "$current" = "{}" ]; then
        echo "{\"${name}\": \"${recipe}\"}" > "${SECRETS_JSON}"
    else
        sed -i 's|}$|,"'"${name}"'": "'"${recipe}"'"}|' "${SECRETS_JSON}"
    fi
}

add_recipe() {
    local name="$1"
    local vault_var="${name}_VAULT"
    local vault_path
    vault_path="$(printenv "$vault_var" 2>/dev/null || true)"
    if [ -n "$vault_path" ]; then
        write_recipe "$name" "vault:${vault_path}"
        echo "  ${name} -> vault:${vault_path}"
        return
    fi
    local val
    val="$(printenv "$name" 2>/dev/null || true)"
    if [ -n "$val" ]; then
        write_recipe "$name" "env:${name}"
        echo "  ${name} -> env:${name}"
    fi
}

echo "Configuring secrets..."
add_recipe "ANTHROPIC_API_KEY"
add_recipe "OPENAI_API_KEY"
add_recipe "VOX_SLACK_USER_TOKEN"
chmod 600 "${SECRETS_JSON}"

# ── Auth validation ───────────────────────────────────────────────────
HAS_CREDENTIALS=false

for var in ANTHROPIC_API_KEY OPENAI_API_KEY OPENROUTER_API_KEY \
           ANTHROPIC_API_KEY_VAULT OPENAI_API_KEY_VAULT OPENROUTER_API_KEY_VAULT; do
    if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
        HAS_CREDENTIALS=true; break
    fi
done

AUTH_JSON="${OMEGON_CONFIG}/auth.json"
if [ -f "$AUTH_JSON" ]; then
    HAS_CREDENTIALS=true
    echo "  auth.json mounted at ${AUTH_JSON}"
    mkdir -p "${HOME}/.config/omegon"
    ln -sf "${AUTH_JSON}" "${HOME}/.config/omegon/auth.json"
fi

if [ "$HAS_CREDENTIALS" = false ] && grep -q '"vault:' "${SECRETS_JSON}" 2>/dev/null; then
    HAS_CREDENTIALS=true
fi

if [ "$HAS_CREDENTIALS" = false ]; then
    echo "ERROR: No LLM credentials found."
    echo "  Provide one of:"
    echo "    -e ANTHROPIC_API_KEY=sk-..."
    echo "    -e ANTHROPIC_API_KEY_VAULT=secret/data/omegon/api#anthropic"
    echo "    -v ~/.config/omegon:/config/omegon:ro  (for OAuth tokens)"
    exit 1
fi

if [ -z "$(printenv VOX_SLACK_USER_TOKEN 2>/dev/null || true)" ] \
   && [ -z "$(printenv VOX_SLACK_USER_TOKEN_VAULT 2>/dev/null || true)" ]; then
    echo "WARNING: VOX_SLACK_USER_TOKEN not set — proxy mode will not connect"
fi

# ── Start ──────────────────────────────────────────────────────────────
echo "Starting omegon daemon..."
exec omegon serve --control-port 7842 "$@"
