#!/bin/sh
set -e

# Unified entrypoint for both bot and proxy Slack containers.
# Config is baked in via VOX_TOML_SOURCE at compose time.
#
# Required env (both modes):
#   ANTHROPIC_API_KEY (or OPENAI_API_KEY, or mounted auth.json)
#
# Bot mode secrets:
#   VOX_SLACK_BOT_TOKEN, VOX_SLACK_APP_TOKEN
#
# Proxy mode secrets:
#   VOX_SLACK_USER_TOKEN
#
# Config override env vars (optional, override baked-in toml):
#   VOX_SLACK_OPERATORS, VOX_SLACK_OPERATOR_ROLES, VOX_SLACK_OPERATOR_GROUPS
#   VOX_SLACK_WORKSPACE, VOX_SLACK_REQUIRE_MENTION, VOX_SLACK_ALLOWED_USERS
#   VOX_SLACK_POSTURE, VOX_SLACK_WATCH_CHANNELS, VOX_SLACK_PROXY_POLL_SECS

OMEGON_HOME="${OMEGON_HOME:-/data/omegon}"
OMEGON_CONFIG="${OMEGON_CONFIG:-/config/omegon}"
SECRETS_JSON="${OMEGON_HOME}/secrets.json"
VOX_TOML="/root/.config/vox/vox.toml"

mkdir -p "${OMEGON_HOME}" "/root/.config/vox"

# ── Vox config ────────────────────────────────────────────────────────
# If VOX_TOML_SOURCE is set (bind-mounted config), copy it in.
# Otherwise use env vars or fall back to whatever is already baked in.
if [ -n "${VOX_TOML_SOURCE}" ] && [ -f "${VOX_TOML_SOURCE}" ]; then
    cp "${VOX_TOML_SOURCE}" "${VOX_TOML}"
    echo "Using config from ${VOX_TOML_SOURCE}"
fi

csv_to_toml_array() {
    local csv="$1"
    if [ -z "$csv" ]; then echo "[]"; return; fi
    printf '['
    first=true
    IFS=','
    for item in $csv; do
        item="$(echo "$item" | xargs)"
        if [ -n "$item" ]; then
            if [ "$first" = true ]; then first=false; else printf ', '; fi
            printf '"%s"' "$item"
        fi
    done
    unset IFS
    printf ']'
}

# Generate bot config from env if relevant vars are set
generate_bot_config() {
    local has_env=false
    for var in VOX_SLACK_BOT_TOKEN VOX_SLACK_OPERATORS VOX_SLACK_OPERATOR_GROUPS \
               VOX_SLACK_WORKSPACE VOX_SLACK_ALLOWED_USERS VOX_SLACK_REQUIRE_MENTION; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_env=true; break
        fi
    done
    if [ "$has_env" = false ]; then return 1; fi

    echo "Generating bot vox.toml from environment..."
    cat > "${VOX_TOML}" <<EOF
# Generated by entrypoint.sh
[slack]
workspace = "${VOX_SLACK_WORKSPACE:-default}"
mode = "bot"
require_mention = ${VOX_SLACK_REQUIRE_MENTION:-true}
operators = $(csv_to_toml_array "${VOX_SLACK_OPERATORS:-}")
operator_groups = $(csv_to_toml_array "${VOX_SLACK_OPERATOR_GROUPS:-}")
allowed_users = $(csv_to_toml_array "${VOX_SLACK_ALLOWED_USERS:-}")
EOF
    return 0
}

# Generate proxy config from env if relevant vars are set
generate_proxy_config() {
    local has_env=false
    for var in VOX_SLACK_USER_TOKEN VOX_SLACK_POSTURE VOX_SLACK_WATCH_CHANNELS \
               VOX_SLACK_PROXY_POLL_SECS; do
        if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
            has_env=true; break
        fi
    done
    if [ "$has_env" = false ]; then return 1; fi

    echo "Generating proxy vox.toml from environment..."
    cat > "${VOX_TOML}" <<EOF
# Generated by entrypoint.sh
[slack]
workspace = "${VOX_SLACK_WORKSPACE:-default}"
mode = "proxy"
posture = "${VOX_SLACK_POSTURE:-observe}"
watch_channels = $(csv_to_toml_array "${VOX_SLACK_WATCH_CHANNELS:-}")
proxy_poll_secs = ${VOX_SLACK_PROXY_POLL_SECS:-30}
EOF
    return 0
}

# Try env-based config (proxy first since VOX_TOML_SOURCE handles the common case)
if [ -z "${VOX_TOML_SOURCE}" ]; then
    generate_proxy_config || generate_bot_config || echo "Using baked-in vox.toml"
fi

# ── Secrets bootstrap ─────────────────────────────────────────────────
echo "{}" > "${SECRETS_JSON}"
chmod 600 "${SECRETS_JSON}"

write_recipe() {
    local name="$1" recipe="$2"
    local current
    current="$(cat "${SECRETS_JSON}")"
    if [ "$current" = "{}" ]; then
        echo "{\"${name}\": \"${recipe}\"}" > "${SECRETS_JSON}"
    else
        sed -i 's|}$|,"'"${name}"'": "'"${recipe}"'"}|' "${SECRETS_JSON}"
    fi
}

add_recipe() {
    local name="$1"
    local vault_var="${name}_VAULT"
    local vault_path
    vault_path="$(printenv "$vault_var" 2>/dev/null || true)"
    if [ -n "$vault_path" ]; then
        write_recipe "$name" "vault:${vault_path}"
        echo "  ${name} -> vault:${vault_path}"
        return
    fi
    local val
    val="$(printenv "$name" 2>/dev/null || true)"
    if [ -n "$val" ]; then
        write_recipe "$name" "env:${name}"
        echo "  ${name} -> env:${name}"
    fi
}

echo "Configuring secrets..."
add_recipe "ANTHROPIC_API_KEY"
add_recipe "OPENAI_API_KEY"
add_recipe "VOX_SLACK_BOT_TOKEN"
add_recipe "VOX_SLACK_APP_TOKEN"
add_recipe "VOX_SLACK_USER_TOKEN"
chmod 600 "${SECRETS_JSON}"

# ── Auth validation ───────────────────────────────────────────────────
HAS_CREDENTIALS=false
for var in ANTHROPIC_API_KEY OPENAI_API_KEY OPENROUTER_API_KEY \
           ANTHROPIC_API_KEY_VAULT OPENAI_API_KEY_VAULT OPENROUTER_API_KEY_VAULT; do
    if [ -n "$(printenv "$var" 2>/dev/null || true)" ]; then
        HAS_CREDENTIALS=true; break
    fi
done

AUTH_JSON="${OMEGON_CONFIG}/auth.json"
if [ -f "$AUTH_JSON" ]; then
    HAS_CREDENTIALS=true
    mkdir -p "${HOME}/.config/omegon"
    ln -sf "${AUTH_JSON}" "${HOME}/.config/omegon/auth.json"
fi

if [ "$HAS_CREDENTIALS" = false ] && grep -q '"vault:' "${SECRETS_JSON}" 2>/dev/null; then
    HAS_CREDENTIALS=true
fi

if [ "$HAS_CREDENTIALS" = false ]; then
    echo "ERROR: No LLM credentials found."
    echo "  -e ANTHROPIC_API_KEY=sk-..."
    exit 1
fi

# ── Start ──────────────────────────────────────────────────────────────
echo "Starting omegon daemon..."
exec omegon serve --control-port 7842 "$@"
